### ISSUE TITLE
makefile:116: recipe for target 'flash' failed

### ISSUE THREAD

**Issue by gis-cc** [Ai-Thinker-Open/Telink_SIG_Mesh#1]
`make flash
python ../../make/Telink_Tools.py -p /dev/ttyUSB2 burn /home/q/Telink_SIG_Mesh/examples/8258_mesh/out/8258_mesh.bin 
make: python: Command not found
../../make/makefile:116: recipe for target 'flash' failed
make: *** [flash] Error 127
`

**Comment by ospanic** [comment]
you need install python3 in you computer
你需要在你的电脑上安装python3

而且，需要预先用专用烧录器烧录bootloader后， 才可以使用串口烧录工具

**Comment by gis-cc** [comment]
> you need install python3 in you computer
> 你需要在你的电脑上安装python3
> 
> 而且，需要预先用专用烧录器烧录bootloader后， 才可以使用串口烧录工具

已经安装了python，如果需要给tb01刷这个mesh还需要购买专用的烧录器吗，最好能在淘宝商品购买链接上标注一下，否则买家会认为买到手就是mesh固件。

**Comment by ospanic** [comment]
是的，我们出厂的模块TB01烧录的是AT固件，若烧录别的固件需要专用的烧录器才行。烧录器网上好像没有卖，即使有也比较贵。我们即将推出可以串口烧录的开发板，敬请期待！

**Comment by gis-cc** [comment]
> 是的，我们出厂的模块TB01烧录的是AT固件，若烧录别的固件需要专用的烧录器才行。烧录器网上好像没有卖，即使有也比较贵。我们即将推出可以串口烧录的开发板，敬请期待！

好吧，还好主任让先买几片试试，这次买得不多，请问AB-01/02出厂固件也是AT固件吗？

**Comment by ospanic** [comment]
AB-02出厂是AT固件。AT系列二次开发需和我们签保密协议，比较麻烦。淘宝上TB-01我会和业务见一下，分成AT固件和Mesh固件。目前我们正在研发TB-02，可支持串口烧录，过几天可以寄给你一片尝鲜。
