### ISSUE TITLE
使用make flash时报错无法上传

### ISSUE THREAD

**Issue by dreamcmi** [Ai-Thinker-Open/Telink_SIG_Mesh#4]
错误信息： 
python3 ../../make/Telink_Tools.py -p /dev/ttyUSB0 burn /home/dreamc/Telink_SIG_Mesh/examples/8258_mesh/out/8258_mesh.bin 
Pyserial is not installed for /usr/bin/python3. Check the README for installation instructions.
Traceback (most recent call last):
  File "../../make/Telink_Tools.py", line 17, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'
../../make/makefile:116: recipe for target 'flash' failed
make: *** [flash] Error 1
 确定usb是在ttyusb0，python版本3.6.9 Ubuntu18.04
请问这是哪里出了问题？

**Comment by ospanic** [comment]
根据错误提示：```ModuleNotFoundError: No module named 'serial'```
你未安装```serial``` Python 模块，百度上面那条信息就能遭到答案。

安装 ```serial```  的方案如下：

```pip install pyserial```

希望能帮到你！

**Comment by xuhongv** [comment]
@dreamcmi 
感谢支持！
请参考环境搭建文档：https://axk.coding.net/s/fad28d26-61a5-4efb-8208-a613565c9b4b

**Comment by dreamcmi** [comment]
> @dreamcmi
> 感谢支持！
> 请参考环境构建文档：[https](https://axk.coding.net/s/fad28d26-61a5-4efb-8208-a613565c9b4b) : //axk.coding.net/s/fad28d26-61a5-4efb-8208-a613565c9b4b[](https://axk.coding.net/s/fad28d26-61a5-4efb-8208-a613565c9b4b)

谢谢 已经成功了
