### ISSUE TITLE
如何连接小爱同学？

### ISSUE THREAD

**Issue by ghost** [Ai-Thinker-Open/Telink_SIG_Mesh#7]
<h2>复现：

---

<pre><font color="#4E9A06"><b>xzw@xzw-RTX2070</b></font>:<font color="#3465A4"><b>~/Telink_SIG_Mesh/example/RGBCW_Ali_Mesh/mesh</b></font>$ gedit mesh_config.h </pre>

<h3>mesh_config.h

...
`125 #if __PROJECT_MESH_PRO__`
`126 #define MESH_USER_DEFINE_MODE 	MESH_NORMAL_MODE // must normal`
`127 #elif __PROJECT_SPIRIT_LPN__`
`128 //#define MESH_USER_DEFINE_MODE 	MESH_SPIRIT_ENABLE // must spirit`
`129 #define MESH_USER_DEFINE_MODE 	MESH_MI_ENABLE`
`130 #else`
`131 //#define MESH_USER_DEFINE_MODE 	MESH_SPIRIT_ENABLE`
`132 #define MESH_USER_DEFINE_MODE 	MESH_MI_ENABLE`
`133 #endif`
...
<h3>然后

<pre><font color="#4E9A06"><b>xzw@xzw-RTX2070</b></font>:<font color="#3465A4"><b>~/Telink_SIG_Mesh/example/RGBCW_Ali_Mesh/mesh</b></font>$ cd ..
<font color="#4E9A06"><b>xzw@xzw-RTX2070</b></font>:<font color="#3465A4"><b>~/Telink_SIG_Mesh/example/RGBCW_Ali_Mesh</b></font>$ make all
</pre>

---

<h2>问题出现

---

<pre>Building file: mesh/ev.c
Building file: mesh/factory_reset.c
Building file: mesh/fast_provision_model.c
Building file: mesh/generic_model.c
Building file: mesh/light.c
mesh/light.c: In function &apos;set_ct_mode&apos;:
mesh/light.c:228:29: error: &apos;ST_TRANS_HSL_HUE&apos; undeclared (first use in this function)
mesh/light.c:228:29: note: each undeclared identifier is reported only once for each function it appears in
mesh/light.c:229:29: error: &apos;ST_TRANS_HSL_SAT&apos; undeclared (first use in this function)
mesh/light.c:230:4: error: &apos;HSL_set&apos; undeclared (first use in this function)
mesh/light.c:230:12: error: expected &apos;;&apos; before &apos;HSL&apos;
mesh/light.c:231:4: error: &apos;RGB_set&apos; undeclared (first use in this function)
mesh/light.c:231:12: error: expected &apos;;&apos; before &apos;RGB&apos;
mesh/light.c:232:4: error: &apos;HSL&apos; undeclared (first use in this function)
mesh/light.c:235:4: warning: implicit declaration of function &apos;HslToRgb&apos;
mesh/light.c:235:18: error: &apos;RGB&apos; undeclared (first use in this function)
make: *** [mesh/mesh.mk:51：out/mesh/light.o] 错误 1
<font color="#4E9A06"><b>xzw@xzw-RTX2070</b></font>:<font color="#3465A4"><b>~/Telink_SIG_Mesh/example/RGBCW_Ali_Mesh</b></font>$</pre>

**Comment by ospanic** [comment]
我们这个固件是针对天猫精灵的，没有对结果小米，所以你的问题我也回复不了。
建议你在Telink官网下载最新的SDK，按照你的思路进行修改再试一试。
